# Generated by Django 5.2.8 on 2025-12-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.IntegerField(auto_created=True),
        ),
    ]
