# Generated by Django 5.2.8 on 2025-12-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_studentprofile_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='class_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.classroom'),
        ),
    ]
