# Generated by Django 5.2.8 on 2025-12-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_studentprofile_class_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='start_date',
            field=models.DateField(),
        ),
    ]
