# Generated by Django 5.2.8 on 2025-12-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_classroom_teacher_alter_attendance_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='class_room',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='class_rooms',
            field=models.ManyToManyField(blank=True, to='core.classroom'),
        ),
    ]
