# Generated by Django 5.2.8 on 2025-12-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_studentprofile_class_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student_profile', 'classroom', 'date')},
        ),
    ]
