# Generated by Django 5.2.8 on 2025-12-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_attendance_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
