# Generated by Django 5.2.8 on 2025-12-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_classroom_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='report_generated_for',
            field=models.DateField(blank=True, null=True),
        ),
    ]
