# Generated by Django 5.2.8 on 2025-12-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_classroom_report_generated_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('secret_code', models.CharField(max_length=50)),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
    ]
